### ISSUE TITLE
Recover database from DeletedDatabase

### ISSUE THREAD

**Issue by aerokite** [k8sdb/apimachinery#17]
We can add another field name `Recover` in `DeletedDatabaseSpec`.

```
type DeletedDatabaseSpec struct {
	AuthSecret *api.SecretVolumeSource `json:"authSecret,omitempty"`
	Destroy bool `json:"destroy,omitempty"`
        Recover bool `json:"recover,omitempty"`
}
```

When `DeletedDatabase` instance will be updated with `recover` field `true`, a new Database TPR instance will be created with existing `PersistentVolume` and `Secret`. 

We can store Database TPR spec in annotation for recover process.

**Comment by TamalSaha** [comment]
cc: @ashiquzzaman33 need to update v1beta2 api once this in implemented. @aerokite co-ordinate with him.

**Comment by TamalSaha** [comment]
This issue was moved to k8sdb/operator#7
