### ISSUE TITLE
Remove volume- prefix from pvc

### ISSUE THREAD

**Issue by TamalSaha** [k8sdb/apimachinery#43]

**Comment by aerokite** [comment]
prefix `volume-` comes from `PersistentVolumeClaim` name. 

When using `VolumeClaimTemplates`, `PVC` name is like `<PersistentVolumeClaim.Name>-<Pod.Name>`

I have used "volume" as name.

@TamalSaha

**Comment by TamalSaha** [comment]
Use `data` as volume name.
