### ISSUE TITLE
Error out if new DB tpr matches an existing Deleted DB?

### ISSUE THREAD

**Issue by TamalSaha** [k8sdb/apimachinery#75]

**Comment by aerokite** [comment]
If new DB name matches with existing DDB, we gives following error and push an event:

- If same Kind, Recover from exisiting DeletedDatabase.
- If different Kind, Invalid DB name, Exists DeletedDatabase of different Kind.

@TamalSaha

**Comment by TamalSaha** [comment]
sgtm!
