### ISSUE TITLE
Check recovery success in DeletedDatabaseController

### ISSUE THREAD

**Issue by aerokite** [k8sdb/apimachinery#83]
Now individual database controllers are responsible for deleting DDB after recovered. 

If it encounters any error before deleting DDB, it causes problem, 
So, DDB remains in Recovering phase forever.

Probable solution:
Let DeletedDatabaseController to check recovery status. 
DDB controller will check for recovered database status. 

Individual database controller will implement that interface method.

**Comment by TamalSaha** [comment]
This issue was moved to k8sdb/operator#14
