### ISSUE TITLE
Unusual behavior of Backup Scheduler

### ISSUE THREAD

**Issue by aerokite** [k8sdb/apimachinery#84]
When backup is scheduled, one snapshot is started immediately.
It this initial snapshot is successed, a cron job is added.

The problem is "job is called frequently so many times."

	23m    Cron Controller    Warning     Failed     Failed to create Snapshot. Reason: thirdpartyresourcedatas.extensions "u-demo-5-20170519-092511" already exists
	23m    Cron Controller    Warning     Failed     Failed to create Snapshot. Reason: thirdpartyresourcedatas.extensions "u-demo-5-20170519-092510" already exists
	23m    Cron Controller    Warning     Failed     Failed to create Snapshot. Reason: thirdpartyresourcedatas.extensions "u-demo-5-20170519-092510" already exists
	23m    Cron Controller    Warning     Failed     Failed to create Snapshot. Reason: thirdpartyresourcedatas.extensions "u-demo-5-20170519-092510" already exists
	23m    Cron Controller    Warning     Failed     Failed to create Snapshot. Reason: thirdpartyresourcedatas.extensions "u-demo-5-20170519-092510" already exists
	23m    Cron Controller    Warning     Failed     Failed to create Snapshot. Reason: thirdpartyresourcedatas.extensions "u-demo-5-20170519-092509" already exists
	23m    Cron Controller    Warning     Failed     Failed to create Snapshot. Reason: thirdpartyresourcedatas.extensions "u-demo-5-20170519-092509" already exists
	23m    Cron Controller    Warning     Failed     Failed to create Snapshot. Reason: thirdpartyresourcedatas.extensions "u-demo-5-20170519-092509" already exists
	23m    Cron Controller    Warning     Failed     Failed to create Snapshot. Reason: thirdpartyresourcedatas.extensions "u-demo-5-20170519-092509" already exists
	23m    Cron Controller    Warning     Failed     Failed to create Snapshot. Reason: thirdpartyresourcedatas.extensions "u-demo-5-20170519-092508" already exists
	23m    Cron Controller    Warning     Failed     Failed to create Snapshot. Reason: thirdpartyresourcedatas.extensions "u-demo-5-20170519-092508" already exists
	23m    Cron Controller    Warning     Failed     Failed to create Snapshot. Reason: thirdpartyresourcedatas.extensions "u-demo-5-20170519-092507" already exists
	23m    Cron Controller    Warning     Failed     Failed to create Snapshot. Reason: thirdpartyresourcedatas.extensions "u-demo-5-20170519-092508" already exists
	23m    Cron Controller    Warning     Failed     Failed to create Snapshot. Reason: thirdpartyresourcedatas.extensions "u-demo-5-20170519-092507" already exists
	23m    Cron Controller    Warning     Failed     Failed to create Snapshot. Reason: thirdpartyresourcedatas.extensions "u-demo-5-20170519-092507" already exists
	23m    Cron Controller    Warning     Failed     Failed to create Snapshot. Reason: thirdpartyresourcedatas.extensions "u-demo-5-20170519-092507" already exists
	23m    Cron Controller    Warning     Failed     Failed to create Snapshot. Reason: thirdpartyresourcedatas.extensions "u-demo-5-20170519-092506" already exists
	23m    Cron Controller    Warning     Failed     Failed to create Snapshot. Reason: thirdpartyresourcedatas.extensions "u-demo-5-20170519-092506" already exists
	23m    Cron Controller    Warning     Failed     Failed to create Snapshot. Reason: thirdpartyresourcedatas.extensions "u-demo-5-20170519-092506" already exists
	23m    Cron Controller    Warning     Failed     Failed to create Snapshot. Reason: thirdpartyresourcedatas.extensions "u-demo-5-20170519-092506" already exists
	23m    Cron Controller    Warning     Failed     Failed to create Snapshot. Reason: thirdpartyresourcedatas.extensions "u-demo-5-20170519-092506" already exists
	23m    Cron Controller    Warning     Failed     Failed to create Snapshot. Reason: thirdpartyresourcedatas.extensions "u-demo-5-20170519-092506" already exists
	23m    Cron Controller    Warning     Failed     Failed to create Snapshot. Reason: thirdpartyresourcedatas.extensions "u-demo-5-20170519-092506" already exists
	23m    Cron Controller    Warning     Failed     Failed to create Snapshot. Reason: thirdpartyresourcedatas.extensions "u-demo-5-20170519-092506" already exists
	23m    Cron Controller    Warning     Failed     Failed to create Snapshot. Reason: thirdpartyresourcedatas.extensions "u-demo-5-20170519-092506" already exists
	23m    Cron Controller    Warning     Failed     Failed to create Snapshot. Reason: thirdpartyresourcedatas.extensions "u-demo-5-20170519-092506" already exists

**Comment by TamalSaha** [comment]
This issue was moved to k8sdb/operator#15
